services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: simplekasten
      POSTGRES_PASSWORD: simplekasten
      POSTGRES_DB: simplekasten
    ports:
      - "5432:5432"
    volumes:
      - simplekasten_pg:/var/lib/postgresql/data

volumes:
  simplekasten_pg:
