// User-facing strings both apps show word for word. Anything that says the
// same thing on desktop and mobile lives here so the two can't drift.
export const COPY = {
  emptyVault: "Your vault is empty — create the first note to get started.",
  emptyGraph: "Nothing to graph yet.",
  editorPlaceholder: "Start writing… type [[ to link to another note",
  titlePlaceholder: "Untitled",
  noLinks: "Link to notes with [[wiki-links]].",
  noBacklinks: "Nothing links here yet.",
  searchPlaceholder: "Search notes, or type a new title…",
  searching: "Searching…",
  createNote: (title: string) => `Create “${title}”`,
  newNote: "New note",
  mapsOfContent: "Maps of content",
  linkedMentions: "Linked mentions",
  attachments: "Attachments",
  saving: "Saving…",
  saved: "Saved",
  deleteNoteTitle: "Delete this note?",
  deleteNoteBody: (title: string) =>
    `“${title || "Untitled"}” will disappear from your notes, search and graph. Links to it will show as unresolved. The file stays on disk, marked deleted.`,
  deleteAttachment: "Remove attachment",
  tags: "Tags",
  tagSearchPlaceholder: "Find or create a tag…",
  createTag: (name: string) => `Create #${name}`,
  noTagsYet: "No tags yet — type a name to create one.",
  tagFromText: "in text",
  tagFromTextHint: "Comes from a #hashtag in the note — edit the text to remove it.",
  invalidTag: "Tags start with a letter and use only letters, digits, _, / or -.",
  noteCount: (count: number, tag: string | null) => `${count} note${count === 1 ? "" : "s"}${tag ? ` · #${tag}` : ""}`,
  reviewTitle: "Review",
  reviewCommandDescription: "Sort your fleeting notes",
  reviewProgress: (current: number, total: number) => `${current} of ${total}`,
  reviewSkip: "Skip",
  reviewDelete: "Delete",
  reviewClose: "Close",
  reviewCaughtUp: "You're all caught up.",
  reviewActionFailed: "That didn't go through — the note is unchanged. Try again.",
} as const;
